language: objective-c
env:
    matrix:
    - XCODE_SCHEME=KeyClip-iOSTests XCODE_SDK=iphonesimulator
    - XCODE_SCHEME=KeyClip-MacTests XCODE_SDK=macosx
script: xctool -project KeyClip.xcodeproj -scheme $XCODE_SCHEME -sdk $XCODE_SDK build test